//* https://substack.com/@systemdesignone/posts
//* https://newsletter.systemdesign.one/p/amazon-s3-durability
//* https://systemdesign.one/leaderboard-system-design/
//* https://newsletter.systemdesign.one/p/aws-scale
//* https://newsletter.systemdesign.one/p/how-does-uber-find-nearby-drivers
//* https://newsletter.systemdesign.one/p/postgresql-scalability
//* https://newsletter.systemdesign.one/p/tinder-architecture
//* https://systemdesign.one/slack-architecture/
//* https://newsletter.systemdesign.one/p/hotstar-scaling
//* https://newsletter.systemdesign.one/p/netflix-microservices
//* https://newsletter.systemdesign.one/p/uber-eta
//* https://newsletter.systemdesign.one/p/zoom-architecture
//* https://newsletter.systemdesign.one/p/virtual-waiting-room
//* https://systemdesign.one/url-shortening-system-design/
